autotest: source
	../refresh.o > refresh2.csv
	../review.o > review2.csv
	../purge.o > purge2.csv
	../prospects.o > prospects2.csv
	../consolidate.o > consolidate2.csv
	../balance.o > balance2.csv

source:
	make -C ../ $@
