language: python
python: "3.5"
script:
  - make CXX=g++-8
  - cppcheck --enable=all .

before_deploy: cp .gitignore_deploy .gitignore

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cppcheck
