language: cpp

python: "3.6"
script:
  - make CXX=g++-8 all profile && mv tmp/readme.md .
  - cppcheck --enable=all .

matrix:
  include:
    os: linux
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
          - g++-8
          - cppcheck

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master
