language: cpp

git:
  depth: false

script:
  - make JOBS=2 source
  - cppcheck --quiet --error-exitcode=1 --enable=all .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env: MATRIX_EVAL="CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-6 # installing clang alone doesn't pull in all the libraries
            - cppcheck
      env: MATRIX_EVAL="CXX=clang++-4.0"

    - os: osx
      osx_image: xcode8
      env: MATRIX_EVAL="CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
