language: python
python: "3.5"
script:
  - make CXX=clang++-5.0 tmp/strategy.o
  - make clean
  - make debug='-O3 -g --coverage' CXX=g++-7
  - bash <(curl -s https://codecov.io/bash)
  - cppcheck --enable=all .

before_deploy: cp .gitignore_deploy .gitignore

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang++-5.0
            - g++-7
            - cppcheck
