language: python
python: "3.6"
script:
  - make CXX=g++-8
  - cppcheck --enable=all .
  - sloccount .

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cppcheck
            - sloccount
