language: cpp

script:
  - make JOBS=2 source
  - make lint

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env: MATRIX_EVAL="CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cppcheck
      env: MATRIX_EVAL="CXX=clang++-4.0"

    - os: osx
      osx_image: xcode8
      env: MATRIX_EVAL="CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
