language: python
python: "3.5"
script:
  - make CXX=clang++-4.0 tmp/strategy.o
  - make clean
  - make CXX=g++-6
  - bash <(curl -s https://codecov.io/bash)
  - which cppcheck && cppcheck -j 2 --enable=all . || true

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang++-4.0
            - g++-6
            - cppcheck
