language: python
python: "3.5"
script:
  - make && cat prospects.csv
  - clang++ --version
  - g++ --version
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: origin/arbitrary_base_currency
